# E.g:

# [user_sprite]
# description = "An sprite which can be assigned to a user"

# [user_sprite.fields]
# blob = { type = "relation", schema = { id = "blob_v1" } }
# description = { type = "str" }
# timestamp = { type = "int" }

# [user_message]
# description = "Messages sent by a user"

# [user_message.fields]
# content = { type = "str" }
# timestamp = { type = "int" }
# from = { type = "relation", schema = { name = "user" } }

# [user]
# description = "A user"

# [user.fields]
# sprite = { type = "relation", schema = { name = "user_sprite" } }
# timestamp = { type = "int" }
# name = { type = "str" }
